name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # We must use macos to compile Metal and run tests natively
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.0'

    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
